#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eticaret
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="eticaret")]
	public partial class eticaretDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertUYELER(UYELER instance);
    partial void UpdateUYELER(UYELER instance);
    partial void DeleteUYELER(UYELER instance);
    partial void Insertilanlar(ilanlar instance);
    partial void Updateilanlar(ilanlar instance);
    partial void Deleteilanlar(ilanlar instance);
    partial void InsertSiparis(Siparis instance);
    partial void UpdateSiparis(Siparis instance);
    partial void DeleteSiparis(Siparis instance);
    partial void InsertGoruntuleme(Goruntuleme instance);
    partial void UpdateGoruntuleme(Goruntuleme instance);
    partial void DeleteGoruntuleme(Goruntuleme instance);
    partial void InsertMesajlar(Mesajlar instance);
    partial void UpdateMesajlar(Mesajlar instance);
    partial void DeleteMesajlar(Mesajlar instance);
    partial void InsertOkunan_mesajlar(Okunan_mesajlar instance);
    partial void UpdateOkunan_mesajlar(Okunan_mesajlar instance);
    partial void DeleteOkunan_mesajlar(Okunan_mesajlar instance);
    #endregion
		
		public eticaretDataContext() : 
				base(global::eticaret.Properties.Settings.Default.eticaretConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public eticaretDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public eticaretDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public eticaretDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public eticaretDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<UYELER> UYELER
		{
			get
			{
				return this.GetTable<UYELER>();
			}
		}
		
		public System.Data.Linq.Table<ilanlar> ilanlar
		{
			get
			{
				return this.GetTable<ilanlar>();
			}
		}
		
		public System.Data.Linq.Table<Siparis> Siparis
		{
			get
			{
				return this.GetTable<Siparis>();
			}
		}
		
		public System.Data.Linq.Table<Goruntuleme> Goruntuleme
		{
			get
			{
				return this.GetTable<Goruntuleme>();
			}
		}
		
		public System.Data.Linq.Table<Ayarlar> Ayarlar
		{
			get
			{
				return this.GetTable<Ayarlar>();
			}
		}
		
		public System.Data.Linq.Table<Mesajlar> Mesajlar
		{
			get
			{
				return this.GetTable<Mesajlar>();
			}
		}
		
		public System.Data.Linq.Table<Okunan_mesajlar> Okunan_mesajlar
		{
			get
			{
				return this.GetTable<Okunan_mesajlar>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UYELER")]
	public partial class UYELER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _kullanici_adi;
		
		private string _parola;
		
		private string _e_posta;
		
		private string _ceptel;
		
		private string _ad;
		
		private string _soyad;
		
		private string _uyelik_tipi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onkullanici_adiChanging(string value);
    partial void Onkullanici_adiChanged();
    partial void OnparolaChanging(string value);
    partial void OnparolaChanged();
    partial void One_postaChanging(string value);
    partial void One_postaChanged();
    partial void OnceptelChanging(string value);
    partial void OnceptelChanged();
    partial void OnadChanging(string value);
    partial void OnadChanged();
    partial void OnsoyadChanging(string value);
    partial void OnsoyadChanged();
    partial void Onuyelik_tipiChanging(string value);
    partial void Onuyelik_tipiChanged();
    #endregion
		
		public UYELER()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kullanici_adi", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string kullanici_adi
		{
			get
			{
				return this._kullanici_adi;
			}
			set
			{
				if ((this._kullanici_adi != value))
				{
					this.Onkullanici_adiChanging(value);
					this.SendPropertyChanging();
					this._kullanici_adi = value;
					this.SendPropertyChanged("kullanici_adi");
					this.Onkullanici_adiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parola", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string parola
		{
			get
			{
				return this._parola;
			}
			set
			{
				if ((this._parola != value))
				{
					this.OnparolaChanging(value);
					this.SendPropertyChanging();
					this._parola = value;
					this.SendPropertyChanged("parola");
					this.OnparolaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_e_posta", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string e_posta
		{
			get
			{
				return this._e_posta;
			}
			set
			{
				if ((this._e_posta != value))
				{
					this.One_postaChanging(value);
					this.SendPropertyChanging();
					this._e_posta = value;
					this.SendPropertyChanged("e_posta");
					this.One_postaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ceptel", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ceptel
		{
			get
			{
				return this._ceptel;
			}
			set
			{
				if ((this._ceptel != value))
				{
					this.OnceptelChanging(value);
					this.SendPropertyChanging();
					this._ceptel = value;
					this.SendPropertyChanged("ceptel");
					this.OnceptelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ad", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ad
		{
			get
			{
				return this._ad;
			}
			set
			{
				if ((this._ad != value))
				{
					this.OnadChanging(value);
					this.SendPropertyChanging();
					this._ad = value;
					this.SendPropertyChanged("ad");
					this.OnadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soyad", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string soyad
		{
			get
			{
				return this._soyad;
			}
			set
			{
				if ((this._soyad != value))
				{
					this.OnsoyadChanging(value);
					this.SendPropertyChanging();
					this._soyad = value;
					this.SendPropertyChanged("soyad");
					this.OnsoyadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uyelik_tipi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string uyelik_tipi
		{
			get
			{
				return this._uyelik_tipi;
			}
			set
			{
				if ((this._uyelik_tipi != value))
				{
					this.Onuyelik_tipiChanging(value);
					this.SendPropertyChanging();
					this._uyelik_tipi = value;
					this.SendPropertyChanged("uyelik_tipi");
					this.Onuyelik_tipiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ilanlar")]
	public partial class ilanlar : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ilan_no;
		
		private bool _oncelik;
		
		private string _kullanici_adi;
		
		private string _ilan_icerigi;
		
		private string _ilan_basligi;
		
		private string _ilan_fiyati;
		
		private string _kategori;
		
		private string _resim_yolu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onilan_noChanging(int value);
    partial void Onilan_noChanged();
    partial void OnoncelikChanging(bool value);
    partial void OnoncelikChanged();
    partial void Onkullanici_adiChanging(string value);
    partial void Onkullanici_adiChanged();
    partial void Onilan_icerigiChanging(string value);
    partial void Onilan_icerigiChanged();
    partial void Onilan_basligiChanging(string value);
    partial void Onilan_basligiChanged();
    partial void Onilan_fiyatiChanging(string value);
    partial void Onilan_fiyatiChanged();
    partial void OnkategoriChanging(string value);
    partial void OnkategoriChanged();
    partial void Onresim_yoluChanging(string value);
    partial void Onresim_yoluChanged();
    #endregion
		
		public ilanlar()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ilan_no", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ilan_no
		{
			get
			{
				return this._ilan_no;
			}
			set
			{
				if ((this._ilan_no != value))
				{
					this.Onilan_noChanging(value);
					this.SendPropertyChanging();
					this._ilan_no = value;
					this.SendPropertyChanged("ilan_no");
					this.Onilan_noChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_oncelik", DbType="Bit NOT NULL")]
		public bool oncelik
		{
			get
			{
				return this._oncelik;
			}
			set
			{
				if ((this._oncelik != value))
				{
					this.OnoncelikChanging(value);
					this.SendPropertyChanging();
					this._oncelik = value;
					this.SendPropertyChanged("oncelik");
					this.OnoncelikChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kullanici_adi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string kullanici_adi
		{
			get
			{
				return this._kullanici_adi;
			}
			set
			{
				if ((this._kullanici_adi != value))
				{
					this.Onkullanici_adiChanging(value);
					this.SendPropertyChanging();
					this._kullanici_adi = value;
					this.SendPropertyChanged("kullanici_adi");
					this.Onkullanici_adiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ilan_icerigi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ilan_icerigi
		{
			get
			{
				return this._ilan_icerigi;
			}
			set
			{
				if ((this._ilan_icerigi != value))
				{
					this.Onilan_icerigiChanging(value);
					this.SendPropertyChanging();
					this._ilan_icerigi = value;
					this.SendPropertyChanged("ilan_icerigi");
					this.Onilan_icerigiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ilan_basligi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ilan_basligi
		{
			get
			{
				return this._ilan_basligi;
			}
			set
			{
				if ((this._ilan_basligi != value))
				{
					this.Onilan_basligiChanging(value);
					this.SendPropertyChanging();
					this._ilan_basligi = value;
					this.SendPropertyChanged("ilan_basligi");
					this.Onilan_basligiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ilan_fiyati", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ilan_fiyati
		{
			get
			{
				return this._ilan_fiyati;
			}
			set
			{
				if ((this._ilan_fiyati != value))
				{
					this.Onilan_fiyatiChanging(value);
					this.SendPropertyChanging();
					this._ilan_fiyati = value;
					this.SendPropertyChanged("ilan_fiyati");
					this.Onilan_fiyatiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kategori", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string kategori
		{
			get
			{
				return this._kategori;
			}
			set
			{
				if ((this._kategori != value))
				{
					this.OnkategoriChanging(value);
					this.SendPropertyChanging();
					this._kategori = value;
					this.SendPropertyChanged("kategori");
					this.OnkategoriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_resim_yolu", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string resim_yolu
		{
			get
			{
				return this._resim_yolu;
			}
			set
			{
				if ((this._resim_yolu != value))
				{
					this.Onresim_yoluChanging(value);
					this.SendPropertyChanging();
					this._resim_yolu = value;
					this.SendPropertyChanged("resim_yolu");
					this.Onresim_yoluChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Siparis")]
	public partial class Siparis : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _siparis_id;
		
		private System.Nullable<int> _ilan_no;
		
		private string _kullanici_adi;
		
		private System.Nullable<System.DateTime> _siparis_tarihi;
		
		private System.Nullable<double> _siparis_ücreti;
		
		private string _siparis_durumu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onsiparis_idChanging(int value);
    partial void Onsiparis_idChanged();
    partial void Onilan_noChanging(System.Nullable<int> value);
    partial void Onilan_noChanged();
    partial void Onkullanici_adiChanging(string value);
    partial void Onkullanici_adiChanged();
    partial void Onsiparis_tarihiChanging(System.Nullable<System.DateTime> value);
    partial void Onsiparis_tarihiChanged();
    partial void Onsiparis_ücretiChanging(System.Nullable<double> value);
    partial void Onsiparis_ücretiChanged();
    partial void Onsiparis_durumuChanging(string value);
    partial void Onsiparis_durumuChanged();
    #endregion
		
		public Siparis()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siparis_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int siparis_id
		{
			get
			{
				return this._siparis_id;
			}
			set
			{
				if ((this._siparis_id != value))
				{
					this.Onsiparis_idChanging(value);
					this.SendPropertyChanging();
					this._siparis_id = value;
					this.SendPropertyChanged("siparis_id");
					this.Onsiparis_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ilan_no", DbType="Int")]
		public System.Nullable<int> ilan_no
		{
			get
			{
				return this._ilan_no;
			}
			set
			{
				if ((this._ilan_no != value))
				{
					this.Onilan_noChanging(value);
					this.SendPropertyChanging();
					this._ilan_no = value;
					this.SendPropertyChanged("ilan_no");
					this.Onilan_noChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kullanici_adi", DbType="NVarChar(50)")]
		public string kullanici_adi
		{
			get
			{
				return this._kullanici_adi;
			}
			set
			{
				if ((this._kullanici_adi != value))
				{
					this.Onkullanici_adiChanging(value);
					this.SendPropertyChanging();
					this._kullanici_adi = value;
					this.SendPropertyChanged("kullanici_adi");
					this.Onkullanici_adiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siparis_tarihi", DbType="DateTime")]
		public System.Nullable<System.DateTime> siparis_tarihi
		{
			get
			{
				return this._siparis_tarihi;
			}
			set
			{
				if ((this._siparis_tarihi != value))
				{
					this.Onsiparis_tarihiChanging(value);
					this.SendPropertyChanging();
					this._siparis_tarihi = value;
					this.SendPropertyChanged("siparis_tarihi");
					this.Onsiparis_tarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siparis_ücreti", DbType="Float")]
		public System.Nullable<double> siparis_ücreti
		{
			get
			{
				return this._siparis_ücreti;
			}
			set
			{
				if ((this._siparis_ücreti != value))
				{
					this.Onsiparis_ücretiChanging(value);
					this.SendPropertyChanging();
					this._siparis_ücreti = value;
					this.SendPropertyChanged("siparis_ücreti");
					this.Onsiparis_ücretiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siparis_durumu", DbType="NVarChar(MAX)")]
		public string siparis_durumu
		{
			get
			{
				return this._siparis_durumu;
			}
			set
			{
				if ((this._siparis_durumu != value))
				{
					this.Onsiparis_durumuChanging(value);
					this.SendPropertyChanging();
					this._siparis_durumu = value;
					this.SendPropertyChanged("siparis_durumu");
					this.Onsiparis_durumuChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Goruntuleme")]
	public partial class Goruntuleme : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ilan_no;
		
		private System.Nullable<int> _goruntulenme_sayisi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onilan_noChanging(int value);
    partial void Onilan_noChanged();
    partial void Ongoruntulenme_sayisiChanging(System.Nullable<int> value);
    partial void Ongoruntulenme_sayisiChanged();
    #endregion
		
		public Goruntuleme()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ilan_no", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ilan_no
		{
			get
			{
				return this._ilan_no;
			}
			set
			{
				if ((this._ilan_no != value))
				{
					this.Onilan_noChanging(value);
					this.SendPropertyChanging();
					this._ilan_no = value;
					this.SendPropertyChanged("ilan_no");
					this.Onilan_noChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_goruntulenme_sayisi", DbType="Int")]
		public System.Nullable<int> goruntulenme_sayisi
		{
			get
			{
				return this._goruntulenme_sayisi;
			}
			set
			{
				if ((this._goruntulenme_sayisi != value))
				{
					this.Ongoruntulenme_sayisiChanging(value);
					this.SendPropertyChanging();
					this._goruntulenme_sayisi = value;
					this.SendPropertyChanged("goruntulenme_sayisi");
					this.Ongoruntulenme_sayisiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ayarlar")]
	public partial class Ayarlar
	{
		
		private int _Ayar_Id;
		
		private string _Ayar_Baslıgı;
		
		private string _Ayar_Icerigi;
		
		private System.DateTime _Tarih;
		
		private string _User_Name;
		
		public Ayarlar()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ayar_Id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Ayar_Id
		{
			get
			{
				return this._Ayar_Id;
			}
			set
			{
				if ((this._Ayar_Id != value))
				{
					this._Ayar_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ayar_Baslıgı", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Ayar_Baslıgı
		{
			get
			{
				return this._Ayar_Baslıgı;
			}
			set
			{
				if ((this._Ayar_Baslıgı != value))
				{
					this._Ayar_Baslıgı = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ayar_Icerigi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Ayar_Icerigi
		{
			get
			{
				return this._Ayar_Icerigi;
			}
			set
			{
				if ((this._Ayar_Icerigi != value))
				{
					this._Ayar_Icerigi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tarih", DbType="DateTime NOT NULL")]
		public System.DateTime Tarih
		{
			get
			{
				return this._Tarih;
			}
			set
			{
				if ((this._Tarih != value))
				{
					this._Tarih = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Name", DbType="NChar(50) NOT NULL", CanBeNull=false)]
		public string User_Name
		{
			get
			{
				return this._User_Name;
			}
			set
			{
				if ((this._User_Name != value))
				{
					this._User_Name = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Mesajlar")]
	public partial class Mesajlar : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Mesaj_Id;
		
		private string _Mesaj_Basligi;
		
		private string _Mesaj_Icerigi;
		
		private string _Gönderen;
		
		private string _Alici;
		
		private System.Nullable<System.DateTime> _Tarih;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMesaj_IdChanging(int value);
    partial void OnMesaj_IdChanged();
    partial void OnMesaj_BasligiChanging(string value);
    partial void OnMesaj_BasligiChanged();
    partial void OnMesaj_IcerigiChanging(string value);
    partial void OnMesaj_IcerigiChanged();
    partial void OnGönderenChanging(string value);
    partial void OnGönderenChanged();
    partial void OnAliciChanging(string value);
    partial void OnAliciChanged();
    partial void OnTarihChanging(System.Nullable<System.DateTime> value);
    partial void OnTarihChanged();
    #endregion
		
		public Mesajlar()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mesaj_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Mesaj_Id
		{
			get
			{
				return this._Mesaj_Id;
			}
			set
			{
				if ((this._Mesaj_Id != value))
				{
					this.OnMesaj_IdChanging(value);
					this.SendPropertyChanging();
					this._Mesaj_Id = value;
					this.SendPropertyChanged("Mesaj_Id");
					this.OnMesaj_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mesaj_Basligi", DbType="NVarChar(50)")]
		public string Mesaj_Basligi
		{
			get
			{
				return this._Mesaj_Basligi;
			}
			set
			{
				if ((this._Mesaj_Basligi != value))
				{
					this.OnMesaj_BasligiChanging(value);
					this.SendPropertyChanging();
					this._Mesaj_Basligi = value;
					this.SendPropertyChanged("Mesaj_Basligi");
					this.OnMesaj_BasligiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mesaj_Icerigi", DbType="NVarChar(MAX)")]
		public string Mesaj_Icerigi
		{
			get
			{
				return this._Mesaj_Icerigi;
			}
			set
			{
				if ((this._Mesaj_Icerigi != value))
				{
					this.OnMesaj_IcerigiChanging(value);
					this.SendPropertyChanging();
					this._Mesaj_Icerigi = value;
					this.SendPropertyChanged("Mesaj_Icerigi");
					this.OnMesaj_IcerigiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gönderen", DbType="NVarChar(50)")]
		public string Gönderen
		{
			get
			{
				return this._Gönderen;
			}
			set
			{
				if ((this._Gönderen != value))
				{
					this.OnGönderenChanging(value);
					this.SendPropertyChanging();
					this._Gönderen = value;
					this.SendPropertyChanged("Gönderen");
					this.OnGönderenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Alici", DbType="NVarChar(50)")]
		public string Alici
		{
			get
			{
				return this._Alici;
			}
			set
			{
				if ((this._Alici != value))
				{
					this.OnAliciChanging(value);
					this.SendPropertyChanging();
					this._Alici = value;
					this.SendPropertyChanged("Alici");
					this.OnAliciChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tarih", DbType="DateTime")]
		public System.Nullable<System.DateTime> Tarih
		{
			get
			{
				return this._Tarih;
			}
			set
			{
				if ((this._Tarih != value))
				{
					this.OnTarihChanging(value);
					this.SendPropertyChanging();
					this._Tarih = value;
					this.SendPropertyChanged("Tarih");
					this.OnTarihChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Okunan_mesajlar")]
	public partial class Okunan_mesajlar : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _kullanici_adi;
		
		private int _mesaj_id;
		
		private System.Nullable<System.DateTime> _tarih;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onkullanici_adiChanging(string value);
    partial void Onkullanici_adiChanged();
    partial void Onmesaj_idChanging(int value);
    partial void Onmesaj_idChanged();
    partial void OntarihChanging(System.Nullable<System.DateTime> value);
    partial void OntarihChanged();
    #endregion
		
		public Okunan_mesajlar()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kullanici_adi", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string kullanici_adi
		{
			get
			{
				return this._kullanici_adi;
			}
			set
			{
				if ((this._kullanici_adi != value))
				{
					this.Onkullanici_adiChanging(value);
					this.SendPropertyChanging();
					this._kullanici_adi = value;
					this.SendPropertyChanged("kullanici_adi");
					this.Onkullanici_adiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mesaj_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int mesaj_id
		{
			get
			{
				return this._mesaj_id;
			}
			set
			{
				if ((this._mesaj_id != value))
				{
					this.Onmesaj_idChanging(value);
					this.SendPropertyChanging();
					this._mesaj_id = value;
					this.SendPropertyChanged("mesaj_id");
					this.Onmesaj_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tarih", DbType="DateTime")]
		public System.Nullable<System.DateTime> tarih
		{
			get
			{
				return this._tarih;
			}
			set
			{
				if ((this._tarih != value))
				{
					this.OntarihChanging(value);
					this.SendPropertyChanging();
					this._tarih = value;
					this.SendPropertyChanged("tarih");
					this.OntarihChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
