#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eticaret
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="eticaret")]
	public partial class eticaretDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertSiparis(Siparis instance);
    partial void UpdateSiparis(Siparis instance);
    partial void DeleteSiparis(Siparis instance);
    partial void InsertMesajlar(Mesajlar instance);
    partial void UpdateMesajlar(Mesajlar instance);
    partial void DeleteMesajlar(Mesajlar instance);
    #endregion
		
		public eticaretDataContext() : 
				base(global::server.Properties.Settings.Default.eticaretConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public eticaretDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public eticaretDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public eticaretDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public eticaretDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Siparis> Siparis
		{
			get
			{
				return this.GetTable<Siparis>();
			}
		}
		
		public System.Data.Linq.Table<Mesajlar> Mesajlar
		{
			get
			{
				return this.GetTable<Mesajlar>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Siparis")]
	public partial class Siparis : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _siparis_id;
		
		private System.Nullable<int> _ilan_no;
		
		private string _kullanici_adi;
		
		private System.Nullable<System.DateTime> _siparis_tarihi;
		
		private System.Nullable<double> _siparis_ücreti;
		
		private string _siparis_durumu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onsiparis_idChanging(int value);
    partial void Onsiparis_idChanged();
    partial void Onilan_noChanging(System.Nullable<int> value);
    partial void Onilan_noChanged();
    partial void Onkullanici_adiChanging(string value);
    partial void Onkullanici_adiChanged();
    partial void Onsiparis_tarihiChanging(System.Nullable<System.DateTime> value);
    partial void Onsiparis_tarihiChanged();
    partial void Onsiparis_ücretiChanging(System.Nullable<double> value);
    partial void Onsiparis_ücretiChanged();
    partial void Onsiparis_durumuChanging(string value);
    partial void Onsiparis_durumuChanged();
    #endregion
		
		public Siparis()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siparis_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int siparis_id
		{
			get
			{
				return this._siparis_id;
			}
			set
			{
				if ((this._siparis_id != value))
				{
					this.Onsiparis_idChanging(value);
					this.SendPropertyChanging();
					this._siparis_id = value;
					this.SendPropertyChanged("siparis_id");
					this.Onsiparis_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ilan_no", DbType="Int")]
		public System.Nullable<int> ilan_no
		{
			get
			{
				return this._ilan_no;
			}
			set
			{
				if ((this._ilan_no != value))
				{
					this.Onilan_noChanging(value);
					this.SendPropertyChanging();
					this._ilan_no = value;
					this.SendPropertyChanged("ilan_no");
					this.Onilan_noChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kullanici_adi", DbType="NVarChar(50)")]
		public string kullanici_adi
		{
			get
			{
				return this._kullanici_adi;
			}
			set
			{
				if ((this._kullanici_adi != value))
				{
					this.Onkullanici_adiChanging(value);
					this.SendPropertyChanging();
					this._kullanici_adi = value;
					this.SendPropertyChanged("kullanici_adi");
					this.Onkullanici_adiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siparis_tarihi", DbType="DateTime")]
		public System.Nullable<System.DateTime> siparis_tarihi
		{
			get
			{
				return this._siparis_tarihi;
			}
			set
			{
				if ((this._siparis_tarihi != value))
				{
					this.Onsiparis_tarihiChanging(value);
					this.SendPropertyChanging();
					this._siparis_tarihi = value;
					this.SendPropertyChanged("siparis_tarihi");
					this.Onsiparis_tarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siparis_ücreti", DbType="Float")]
		public System.Nullable<double> siparis_ücreti
		{
			get
			{
				return this._siparis_ücreti;
			}
			set
			{
				if ((this._siparis_ücreti != value))
				{
					this.Onsiparis_ücretiChanging(value);
					this.SendPropertyChanging();
					this._siparis_ücreti = value;
					this.SendPropertyChanged("siparis_ücreti");
					this.Onsiparis_ücretiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siparis_durumu", DbType="NVarChar(MAX)")]
		public string siparis_durumu
		{
			get
			{
				return this._siparis_durumu;
			}
			set
			{
				if ((this._siparis_durumu != value))
				{
					this.Onsiparis_durumuChanging(value);
					this.SendPropertyChanging();
					this._siparis_durumu = value;
					this.SendPropertyChanged("siparis_durumu");
					this.Onsiparis_durumuChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Mesajlar")]
	public partial class Mesajlar : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Mesaj_Id;
		
		private string _Mesaj_Basligi;
		
		private string _Mesaj_Icerigi;
		
		private string _Gönderen;
		
		private string _Alici;
		
		private System.Nullable<System.DateTime> _Tarih;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMesaj_IdChanging(int value);
    partial void OnMesaj_IdChanged();
    partial void OnMesaj_BasligiChanging(string value);
    partial void OnMesaj_BasligiChanged();
    partial void OnMesaj_IcerigiChanging(string value);
    partial void OnMesaj_IcerigiChanged();
    partial void OnGönderenChanging(string value);
    partial void OnGönderenChanged();
    partial void OnAliciChanging(string value);
    partial void OnAliciChanged();
    partial void OnTarihChanging(System.Nullable<System.DateTime> value);
    partial void OnTarihChanged();
    #endregion
		
		public Mesajlar()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mesaj_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Mesaj_Id
		{
			get
			{
				return this._Mesaj_Id;
			}
			set
			{
				if ((this._Mesaj_Id != value))
				{
					this.OnMesaj_IdChanging(value);
					this.SendPropertyChanging();
					this._Mesaj_Id = value;
					this.SendPropertyChanged("Mesaj_Id");
					this.OnMesaj_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mesaj_Basligi", DbType="NVarChar(50)")]
		public string Mesaj_Basligi
		{
			get
			{
				return this._Mesaj_Basligi;
			}
			set
			{
				if ((this._Mesaj_Basligi != value))
				{
					this.OnMesaj_BasligiChanging(value);
					this.SendPropertyChanging();
					this._Mesaj_Basligi = value;
					this.SendPropertyChanged("Mesaj_Basligi");
					this.OnMesaj_BasligiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mesaj_Icerigi", DbType="NVarChar(MAX)")]
		public string Mesaj_Icerigi
		{
			get
			{
				return this._Mesaj_Icerigi;
			}
			set
			{
				if ((this._Mesaj_Icerigi != value))
				{
					this.OnMesaj_IcerigiChanging(value);
					this.SendPropertyChanging();
					this._Mesaj_Icerigi = value;
					this.SendPropertyChanged("Mesaj_Icerigi");
					this.OnMesaj_IcerigiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gönderen", DbType="NVarChar(50)")]
		public string Gönderen
		{
			get
			{
				return this._Gönderen;
			}
			set
			{
				if ((this._Gönderen != value))
				{
					this.OnGönderenChanging(value);
					this.SendPropertyChanging();
					this._Gönderen = value;
					this.SendPropertyChanged("Gönderen");
					this.OnGönderenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Alici", DbType="NVarChar(50)")]
		public string Alici
		{
			get
			{
				return this._Alici;
			}
			set
			{
				if ((this._Alici != value))
				{
					this.OnAliciChanging(value);
					this.SendPropertyChanging();
					this._Alici = value;
					this.SendPropertyChanged("Alici");
					this.OnAliciChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tarih", DbType="DateTime")]
		public System.Nullable<System.DateTime> Tarih
		{
			get
			{
				return this._Tarih;
			}
			set
			{
				if ((this._Tarih != value))
				{
					this.OnTarihChanging(value);
					this.SendPropertyChanging();
					this._Tarih = value;
					this.SendPropertyChanged("Tarih");
					this.OnTarihChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
